# Generated by Django 4.1.6 on 2023-02-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=255, null=True)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='rasmlar')),
                ('tanlov', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcat.catagory')),
            ],
        ),
    ]
